export const CANTONS = {
    'AG': 'Aargau',
    'AR': 'Appenzell A',
    'AI': 'Appenzell I',
    'BE': 'Bern',
    'BL': 'Basel-Land.',
    'BS': 'Basel-Stadt',
    'FR': 'Fribourg',
    'GE': 'Geneva',
    'GL': 'Glarus',
    'GR': 'Grisons',
    'JU': 'Jura',
    'LU': 'Luzern',
    'NE': 'Neuchâtel',
    'NW': 'Nidwalden',
    'OW': 'Obwalden',
    'SH': 'Schaffhausen',
    'SO': 'Solothurn',
    'SG': 'St. Gallen',
    'SZ': 'Schwyz',
    'TI': 'Ticino',
    'TG': 'Thurgau',
    'UR': 'Uri',
    'VD': 'Vaud',
    'VS': 'Valais',
    'ZG': 'Zug',
    'ZH': 'Zürich',
}

export const RENTAL_RANGE = {
    short: "1-4 months",
    medium: "4-8 months",
    max: "9+ months",
};
